apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-ingress-gateway
  namespace: apps
spec:
  selector:
    matchLabels:
      app: httpbin
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        # Identidad EXACTA que vimos en tus logs anteriores
        - "spiffe://example.org/ns/istio-ingress/sa/istio-ingress"
        # Permitimos también al gateway estándar por si acaso
        - "spiffe://example.org/ns/istio-ingress/sa/istio-ingressgateway"
        # Permitimos al sleep-admin para verificar que esto funciona
        - "spiffe://example.org/ns/istio-ingress/sa/sleep-admin"
        # Permitimos el acceso interno normal
        - "spiffe://example.org/ns/apps/sa/sleep"
        - "cluster.local/ns/apps/sa/sleep"
