apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: httpbin-spire-mtls
  namespace: apps
spec:
  # 1. Match the httpbin service
  host: httpbin.apps.svc.cluster.local
  trafficPolicy:
    tls:
      # 2. Force Istio Mutual TLS
      mode: ISTIO_MUTUAL
      # 3. CRITICAL: Explicitly tell Istio to verify this SPIFFE ID
      subjectAltNames:
        - "spiffe://example.org/ns/apps/sa/httpbin"
