apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: httpbin-trust-spire
  namespace: apps
spec:
  workloadSelector:
    labels:
      app: httpbin
  configPatches:
  - applyTo: FILTER_CHAIN
    match:
      context: SIDECAR_INBOUND
      listener:
        name: virtualInbound
        filterChain:
          # ESTO ES LO QUE ENCONTRAMOS EN TU JSON
          name: "0.0.0.0_80"
    patch:
      operation: MERGE
      value:
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
            require_client_certificate: true
            common_tls_context:
              # Forzamos protocolos estándar
              alpn_protocols: ["h2", "http/1.1"]
              # AQUÍ ESTÁ EL CAMBIO: Usamos el archivo en lugar de SDS
              validation_context:
                trusted_ca:
                  filename: "/var/run/secrets/spire-bundle/root-cert.pem"
                # Opcional: Validar que venga del dominio correcto
                match_subject_alt_names:
                  - prefix: "spiffe://example.org/"
