apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: httpbin-trust-spire
  namespace: apps
spec:
  workloadSelector:
    labels:
      app: httpbin
  configPatches:
  - applyTo: FILTER_CHAIN
    match:
      context: SIDECAR_INBOUND
      listener:
        name: "virtualInbound"   # <--- Uses the name we just found
        filterChain:
          transportProtocol: "tls" # Target the mTLS chain seen in your output
    patch:
      operation: MERGE
      value:
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
            common_tls_context:
              validation_context:
                trusted_ca:
                  filename: "/var/run/secrets/spire-bundle/root-cert.pem"
