apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 9
  name: httpbin
  namespace: apps
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: httpbin
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2026-02-03T23:46:53-03:00"
        sidecar.istio.io/inject: "true"
        sidecar.istio.io/userVolume: |
          [{"name":"spire-root-cert","configMap":{"name":"spire-bundle"}}]
        sidecar.istio.io/userVolumeMount: '[{"name":"custom-root-cert","mountPath":"/var/run/secrets/istio","readOnly":true}]'  
      labels:
        app: httpbin
        spiffe.io/spire-managed-identity: "true"
        version: v1
    spec:
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: httpbin
      serviceAccountName: httpbin
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2026-02-04T02:45:42Z"
    lastUpdateTime: "2026-02-04T02:45:42Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2026-02-04T02:38:00Z"
    lastUpdateTime: "2026-02-04T02:46:43Z"
    message: Created new replica set "httpbin-56f9b5b79f"
    reason: NewReplicaSetCreated
    status: "True"
    type: Progressing
  - lastTransitionTime: "2026-02-04T02:46:53Z"
    lastUpdateTime: "2026-02-04T02:46:53Z"
    message: 'Pod "httpbin-555d5c78f9-5strm" is invalid: spec.initContainers[1].volumeMounts[9].mountPath:
      Invalid value: "/var/run/secrets/istio": must be unique'
    reason: FailedCreate
    status: "True"
    type: ReplicaFailure
  observedGeneration: 9
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 1
