apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin
  namespace: apps
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: apps
  labels:
    app: httpbin
    service: httpbin
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
  selector:
    app: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
        # TRIGGER: SPIRE Auto-Registration
        spiffe.io/spire-managed-identity: "true"
      annotations:
        # INJECTION: Standard Istio + Custom SPIRE Volume
        sidecar.istio.io/inject: "true"
        sidecar.istio.io/userVolume: '[{"name":"workload-socket","csi":{"driver":"csi.spiffe.io","readOnly":true}}]'
        sidecar.istio.io/userVolumeMount: '[{"name":"workload-socket","mountPath":"/run/secrets/workload-spiffe-uds","readOnly":true}]'
    spec:
      serviceAccountName: httpbin
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 80
