apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
        # Trigger SPIRE Identity
        spiffe.io/spire-managed-identity: "true"
      annotations:
        # 1. Inject the Sidecar + SPIRE Socket
        inject.istio.io/templates: "sidecar,spire"
        
        # 2. MOUNT THE TRUST BUNDLE (The "Manual Trust Fix")
        # This tells Istio: "Please mount the 'spire-bundle' ConfigMap to /var/run/secrets/spire-bundle"
        sidecar.istio.io/userVolume: '[{"name":"spire-bundle", "configMap":{"name":"spire-bundle"}}]'
        sidecar.istio.io/userVolumeMount: '[{"name":"spire-bundle", "mountPath":"/var/run/secrets/spire-bundle", "readOnly":true}]'
    spec:
      serviceAccountName: httpbin
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 80
