apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin
  namespace: apps
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: apps
  labels:
    app: httpbin
    service: httpbin
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
  selector:
    app: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
        # Tells SPIRE Agent to generate an identity for this Pod
        spiffe.io/spire-managed-identity: "true"
      annotations:
        # 1. Standard Sidecar Injection (Avoids the 'Duplicate Proxy' template bug)
        sidecar.istio.io/inject: "true"

        # 2. DEFINE VOLUMES:
        #    - workload-socket: The SPIRE Agent CSI Driver (Identity)
        #    - spire-bundle: The ConfigMap with the Root CA (Trust)
        sidecar.istio.io/userVolume: |
          [
            {"name":"workload-socket", "csi":{"driver":"csi.spiffe.io", "readOnly":true}},
            {"name":"spire-bundle", "configMap":{"name":"spire-bundle"}}
          ]

        # 3. MOUNT VOLUMES (Into the Sidecar):
        sidecar.istio.io/userVolumeMount: |
          [
            {"name":"workload-socket", "mountPath":"/run/secrets/workload-spiffe-uds", "readOnly":true},
            {"name":"spire-bundle", "mountPath":"/var/run/secrets/spire-bundle", "readOnly":true}
          ]
    spec:
      serviceAccountName: httpbin
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 80
