apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: httpbin-trust-spire
  namespace: apps
spec:
  workloadSelector:
    labels:
      app: httpbin
  configPatches:
  - applyTo: FILTER_CHAIN
    match:
      context: SIDECAR_INBOUND
      listener:
        name: virtualInbound
        filterChain:
          destinationPort: 80    # Apunta a la cadena "0.0.0.0_80" de tu JSON
          transportProtocol: tls # Apunta solo a la versión mTLS
    patch:
      operation: REPLACE         # <--- CLAVE: Reemplaza, no mezcla
      value:
        # Reconstruimos la cadena con los mismos filtros pero cambiando el socket TLS
        filterChainMatch:
          destinationPort: 80
          transportProtocol: tls
          applicationProtocols: ["istio", "istio-peer-exchange", "istio-http/1.0", "istio-http/1.1", "istio-h2"]
        filters:
        - name: istio.metadata_exchange
          typedConfig:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            typeUrl: type.googleapis.com/envoy.tcp.metadataexchange.config.MetadataExchange
            value:
              protocol: istio-peer-exchange
              enable_discovery: true
        - name: envoy.filters.network.http_connection_manager
          typedConfig:
            "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            statPrefix: "inbound_0.0.0.0_80;"
            routeConfig:
              name: "inbound|80||"
              virtualHosts:
              - name: "inbound|http|8000"
                domains: ["*"]
                routes:
                - name: "default"
                  match: { prefix: "/" }
                  route:
                    cluster: "inbound|80||"
                    timeout: "0s"
                    maxStreamDuration: { maxStreamDuration: "0s", grpcTimeoutHeaderMax: "0s" }
                  decorator:
                    operation: "httpbin.apps.svc.cluster.local:8000/*"
            httpFilters:
            - name: istio.metadata_exchange
              typedConfig:
                "@type": type.googleapis.com/udpa.type.v1.TypedStruct
                typeUrl: type.googleapis.com/io.istio.http.peer_metadata.Config
                value:
                  downstream_discovery: [ { istio_headers: {} }, { workload_discovery: {} } ]
                  downstream_propagation: [ { istio_headers: {} } ]
            - name: envoy.filters.http.router
              typedConfig:
                "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
        transport_socket: # <--- AQUÍ ESTÁ EL CAMBIO
          name: envoy.transport_sockets.tls
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
            require_client_certificate: true
            common_tls_context:
              alpn_protocols: ["h2", "http/1.1"]
              tls_params:
                tls_minimum_protocol_version: TLSv1_2
                tls_maximum_protocol_version: TLSv1_3
              validation_context: # Usamos ValidationContext simple (Archivo)
                trusted_ca:
                  filename: "/var/run/secrets/spire-bundle/root-cert.pem"
                match_subject_alt_names: # Validamos el dominio de SPIRE
                  - prefix: "spiffe://example.org/"
